### ISSUE TITLE
Algoritmo de Reducción

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/panel#2]
Es necesario programar el algoritmo de Reducción de datos que permita analizar y comparar los datos de la colección militar en Mongo Db, con otras bases de datos, mediante archivos en formato excel

**Comment by gesaodin** [comment]
Resuelta en el tunel con panel
785eac07a7af253afa9af4fdce1480b8730e4829

**Comment by gesaodin** [comment]
Resuelta en el tunel con panel
785eac07a7af253afa9af4fdce1480b8730e4829
