### ISSUE TITLE
Modulo de configuración del panel de control

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/panel#4]
Es necesario diseñar y programar el modulo de configuración en el panel de control para bloqueo, respaldo, cambio de privilegios y recuperación de usuarios del sistama

**Comment by gesaodin** [comment]
Interfaz Gráfica
![image](https://user-images.githubusercontent.com/11463651/37457728-29453c8e-2819-11e8-8529-824d6da48f09.png)
