### ISSUE TITLE
Desbloqueo de Carnet

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/panel#7]
Es necesario programar el menú con la función que permita desbloquear la impresión del TIM, al cual debe tener acceso el usuario con privilegios de aprobación, con alerta o notificación del caso

**Comment by gesaodin** [comment]
La interfaz se diseño para el desbloqueo del carnet
![image](https://user-images.githubusercontent.com/11463651/37457473-7c1dd534-2818-11e8-91ac-eca79c2d19bd.png)
