### ISSUE TITLE
Limpieza de Bandejas de estatus de la tarjeta de identificación

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/panel#8]
Es necesario programar una función que permita limpiar diariamente las bandejas de aprobación e impresión de TIM

**Comment by gesaodin** [comment]
Actividad  entre panel y tunel
Panel: 0d306f59253040e52127a2700c6c2bc5c863ded4
Tunel: 73b042da080e1de864a708c864d5ae73e7e2a760

**Comment by gesaodin** [comment]
Enrutador.HandleFunc("/ipsfa/api/carnet/limpiar/{estatus}/{sucursal}", wUsuario.ValidarToken(wcar.Limpiar)).Methods("GET")

//Limpiar Carnet
func (tim *Carnet) Limpiar(estatus int, sucursal string) ( err error) {
	c := sys.MGOSession.DB(sys.CBASE).C(sys.CTIM)
	_, err = c.UpdateAll(bson.M{"estatus": estatus, "usuario": sucursal}, bson.M{"$set": bson.M{"estatus" : 5} })
	if err != nil {
		fmt.Println("No se lograron actualizar los datos")
		return
	}
	return
}
