### ISSUE TITLE
Notificaciones de Procesos

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/panel#9]
Es necesario programar y activar las notificaciones de proceso en ejecución (cargando) en las pantallas correspondientes

**Comment by gesaodin** [comment]
var promesa = CargarAPI({
        sURL: url,
        metodo: 'GET',
        valores: '',
    })
    .then(function(xhRequest) {
        var datos = JSON.parse(xhRequest.responseText);
        if (datos.tipo == 0){
            $.notify("El servidor no esta disponible...", {
                animate: {
                    enter: 'animated bounceIn',
                    exit: 'animated bounceOut'
                },
              type: 'danger'
            });
        }else{
          $.notify("proceso finalizado", "success");
        }
    });
